config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :articles do
    resources :comments, only: [:create, :destroy]
  end

  root 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  has_many :comments

  validates :title, presence: true
  validates :content, presence: true
  validates :is_draft, inclusion: { in: [true, false] }

  after_initialize do
    self.is_draft = false if new_record?
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user

  validates :content,
            presence: true,
            length: { maximum: 250 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles
  has_many :comments

  validates :first_name,
            presence: true,
            allow_blank: false,
            length: { maximum: 80 }

  validates :last_name,
            presence: true,
            allow_blank: false,
            length: { maximum: 80 }

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @articles = Article.all.order('created_at DESC')
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id

    if @article.save
      flash[:notice] = 'New article successfully added!'
      redirect_to @article
    else
      flash[:error] = 'Wrong submission. Try again!'
      render :new
    end
  end

  def show
    @comment = Comment.new
  end

  def edit; end

  def update
    if @article.update(article_params)
      flash[:notice] = 'Article successfully edited!'
      redirect_to @article
    else
      flash[:alert] = 'Wrong submission. Try again!'
      render :edit
    end
  end

  def destroy
    @article.destroy
    flash[:notice] = 'Article successfully deleted!'

    redirect_to articles_path
  end

  private

  def find_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content, :user_id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_article, only: [:create, :destroy]
  before_action :authenticate_user!, except: [:create, :destroy]

  def create
    @comment = @article.comments.new(comment_params)
    @comment.user = current_user

    if @comment.save
      flash[:notice] = 'New comment successfully added!'
      redirect_to @article
    else
      flash[:error] = 'Wrong submission. Try again!'
      render :index
    end
  end

  def destroy
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    flash[:notice] = 'Comment successfully deleted!'
    redirect_to @article
  end

  private

  def find_article
    @article = Article.find(params[:article_id])
  end

  def find_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= form_with(model: @article, local: true) do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title, required: true %><br>

  <%= form.label :content %>
  <%= form.text_area :content, required: true %><br>

  <%= form.submit %>
<% end %>

<%= link_to 'Cancel', article_path(@article) %>

app/views/articles/index.html.erb
<h1>Articles</h1>

<ul>
<% @articles.each do |article| %>
  <li>
    <%= article.title %>
    <%= link_to 'Show', article %>
    <% if user_signed_in? %>
       | <%= link_to 'Edit', edit_article_path(article), class: "edit-link" %> |
      <%= link_to 'Delete', article_path(article), method: :delete %>
    <% end %>
  </li>
<% end %>
</ul>

<% if user_signed_in? %>
  <%= link_to 'New', new_article_path %>
<% end %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= form_with(model: @article, local: true) do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title, required: true %><br>

  <%= form.label :content %>
  <%= form.text_area :content, required: true %><br>

  <%= form.submit %>
<% end %>

<%= link_to 'Cancel', articles_path %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.content %></p>

<%= link_to 'Home', articles_path %>
<% if user_signed_in? %>
  | <%= link_to 'Edit', edit_article_path(@article) %> |
  <%= link_to 'Delete', article_path(@article), method: :delete %>
<% end %>

<% if user_signed_in? %>
  <h5>Write a comment:</h5>
  <%= form_with(model: @comment, url: article_comments_path(@article), local: true) do |form| %>
    <%= form.label :content %><br>
    <%= form.text_field :content, required: true %><br>
    <%= form.submit %>
  <% end %>
<% else %>
  <p>Wanna write a comment? <%= link_to 'Sign in', new_user_session_path %> or <%= link_to 'sign up', new_user_registration_path %> now!</p>
<% end %>

<div style="max-width: 300px">
  <h5>Comments</h5>
  <% @article.comments.each do |comment| %>
    <p><%= comment.content %></p>
    <small>written by <%= comment.user.full_name %></small><br>
    <% if user_signed_in? && comment.user == current_user %>
      <%= link_to 'Delete comment', article_comment_path(@article, comment), method: :delete %>
    <% end %>
    <hr>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestingMyBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign in", new_user_session_path %> | <%= link_to "Sign up", new_user_registration_path %>
    <% end %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>